name: scaffold
dependencies: 
  angel_model: ^1.0.0
  angel_serialize: ^1.0.0-alpha
  console: ^2.0.0
  json_rpc_2: ^2.0.0
  resource: ^2.0.0
  stream_channel: ^1.0.0
dev_dependencies: 
  angel_serialize_generator: ^1.0.0-alpha
  build_runner: ^0.5.0
